quarkus.application.name=cosmos-attachment-service
quarkus.http.port=8083

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cosmos_attachment_db
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres

%dev.quarkus.s3.endpoint-override=http://localhost:9000
%dev.quarkus.s3.aws.credentials.static-provider.access-key-id=minioadmin
%dev.quarkus.s3.aws.credentials.static-provider.secret-access-key=minioadmin

# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Liquibase
liquibase.enabled=${LIQUIBASE_ENABLED:true}
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml
quarkus.liquibase.migrate-at-start=true

# MinIO Storage Configuration (via Amazon S3)
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.path-style-access=true
quarkus.s3.sync-client.type=url

# Sécurité désactivée (mode public)
quarkus.oidc.enabled=false
quarkus.http.auth.permission.public.paths=/*
quarkus.http.auth.permission.public.policy=permit

# Configuraton Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/cosmos-attachment-swagger
quarkus.swagger-ui.theme=original
quarkus.smallrye-openapi.path=/cosmos-attachment-openapi


# Limites & CORS
quarkus.http.limits.max-body-size=20M
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PATCH,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,X-Tenant-ID

# Configuration CDI
quarkus.arc.auto-inject-fields=true
quarkus.arc.remove-unused-beans=false

# Tracing
quarkus.otel.enabled=false