quarkus.application.name=cosmos-attachment-service
quarkus.http.port=8083

# --- 1. Variables Locales (Configuration Dev) ---
%dev.DB_HOST=localhost
%dev.DB_PORT=5432
%dev.DB_NAME=cosmos_attachment_db
%dev.DB_USERNAME=postgres
%dev.DB_PASSWORD=postgres

%dev.KC_URL=http://localhost:8081
%dev.KC_REALM=cosmos-realm
%dev.KC_CLIENT_ID=cosmos-attachment-service
%dev.KC_CLIENT_SECRET=FNKENeYiEnWIEFpEAILR2KqhFGaJExCP

# --- 2. BDD Configuration ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

# Multi-tenant
quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# --- 3. MinIO Storage Configuration ---
cosmos.minio.url=http://localhost:9000
cosmos.minio.access-key=minioadmin
cosmos.minio.secret-key=minioadmin

# --- 4. OIDC Client Config (Sécurité) ---
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=${KC_URL}/realms/${KC_REALM}
quarkus.oidc.client-id=${KC_CLIENT_ID}
quarkus.oidc.credentials.secret=${KC_CLIENT_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.authentication.mechanism=bearer

# --- 5. Sécurité & Swagger UI ---
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/cosmos-attachment-swagger
quarkus.smallrye-openapi.path=/cosmos-attachment-openapi

# Permissions
quarkus.http.auth.permission.public.paths=/cosmos-attachment-swagger/*,/cosmos-attachment-openapi/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# --- 6. Limites & CORS ---
quarkus.http.limits.max-body-size=20M
quarkus.http.cors=true
quarkus.http.cors.origins=*

# --- 7. Tracing & GraphQL (Optionnel pour test local) ---
quarkus.smallrye-graphql.root-path=/acc-apis/graphql
quarkus.otel.enabled=false